name: Build Branch

on:
  push:
    branches: [ main, develop, non-prod ]
  pull_request:
    branches: [ '*' ]
jobs:
  extract_branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract.outputs.var }}
    steps:
      - id: extract
        run: echo "::set-output name=var::${GITHUB_REF##*/}"
  build_and_test:
    env:
      BRANCH_NAME: ${{ needs.extract_branch.outputs.branch_name }}
    needs: extract_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run check-types
      - run: npm run lint:ci
      - run: npm run test:ci
      - run: npm run build
  publish-npm:
    needs:
      - extract_branch
      - build_and_test
    if: ${{ needs.extract_branch.outputs.branch_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.platforms.engineering
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}