name: My Org Branch CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start
        run: echo "Starting GH Workflow for Branches."

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Finish
        run: echo "It finished!"
