name: Main build

on:
  push:
    branches: [ main ]

jobs:
  Build_Main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start
        run: | 
          echo "Starting GH Workflow for Branches."
          npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Finish
        run: echo "It finished!"
