name: Publish

on:
  push:
    branches: [ main, develop, non-prod ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          repository: bfaulk96-org/.github
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: v1
          path: ./.github/org-actions
      - name: Build and Test
        id: build_and_test
        uses: ./.github/org-actions/actions/build-and-test
  publish:
    env:
    if: ${{ contains(env.GITHUB_REF, "main") }}
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
#          registry-url: https://npm.platforms.engineering
          registry-url: https://registry.npmjs.org
      - name: Set Up npm
        run: npm config set registry https://registry.npmjs.org
#      - run: npm config set @other:registry https://npm.platforms.engineering
#      - name: Install Dependencies
#        run: npm ci
      - name: Publish
        run: echo Publishing...
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  slackNotify:
    needs: [ build_and_test, publish ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
          with:
            repository: bfaulk96-org/.github
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            ref: v1
            path: ./.github/org-actions
      - name: Slack Notify
        id: slack_notify
        uses: ./.github/org-actions/actions/slack-notify