name: Publish
env:
  shared_lib_version: v1.1.2
  shared_lib_path: ./.github/org-actions
  shared_lib_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  shared_lib_repo: bfaulk96-org/.github
on:
  push:
    branches: [ main, develop, non-prod ]
jobs:
#  checkout_shared_lib:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2 # https://github.com/actions/checkout
#        with:
#          repository: ${{env.shared_lib_repo}}
#          ssh-key: ${{env.shared_lib_private_key}}
#          ref: ${{env.shared_lib_version}}
#          path: ${{env.shared_lib_path}}
#      - name: Upload shared actions
#        uses: actions/upload-artifact@v2
#        with:
#          name: shared
#          path: ${{env.shared_lib_path}}/actions
#          if-no-files-found: error
#          retention-days: 1
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get shared actions
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          repository: ${{env.shared_lib_repo}}
          ssh-key: ${{env.shared_lib_private_key}}
          ref: ${{env.shared_lib_version}}
          path: ${{env.shared_lib_path}}
      - name: Build and Test
        id: build_and_test
        uses: ./.github/org-actions/actions/build-and-test
  publish:
    if: ${{ github.github_ref == 'refs/heads/main' }}
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
#          registry-url: https://npm.platforms.engineering
          registry-url: https://registry.npmjs.org
      - name: Set Up npm
        run: npm config set registry https://registry.npmjs.org
#      - run: npm config set @other:registry https://npm.platforms.engineering
#      - name: Install Dependencies
#        run: npm ci
      - name: Publish
        run: echo Publishing...
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  slackNotify:
    needs: [ build_and_test, publish ]
    runs-on: ubuntu-latest
    steps:
#      - name: Download shared actions
#        uses: actions/download-artifact@v2
#        with:
#          name: shared
#          path: ${{env.shared_lib_path}}
      - name: Get shared actions
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          repository: ${{env.shared_lib_repo}}
          ssh-key: ${{env.shared_lib_private_key}}
          ref: ${{env.shared_lib_version}}
          path: ${{env.shared_lib_path}}
      - name: Slack Notify
        id: slack_notify
        uses: ./.github/org-actions/actions/build-and-test