name: Build & Test

on:
  pull_request:
    branches: [ '*' ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          rm -rf .git
          rm -rf node_modules/.cache
      - name: Check Types
        run: npm run check-types
      - name: Lint Repo
        run: npm run lint:ci
      - name: Run Tests
        run: npm run test:ci
